### ISSUE TITLE
Expose CLLocationManagerDelegate protocol implementation

### ISSUE THREAD

**Issue by Rajveer86** [intuit/LocationManager#26]
I have a subclass of INTULocationManager in which I'd like to perform some additional setup when location authorisation changes, however I can't override and then call super's locationManager:didChangeAuthorizationStatus: because INTULocationManager implements the CLLocationManager protocol in it's empty category interface rather than the class interface itself. Can this be changed?

**Comment by smileyborg** [comment]
Hi @Rajveer86,

Sorry for the delay in responding; I was out on vacation. Anyways, INTULocationManager wasn't really designed to be subclassed, although there isn't any reason you shouldn't do so.

I'm a big fan of minimizing the public interface as much as possible. Instead of putting the CLLocationManagerDelegate protocol conformance in the public header, what if we add a new [subclass category header](http://stackoverflow.com/a/6103044/796419) to do this? For example:

    // INTULocationManager+Subclass.h
    
    @interface INTULocationManager (Subclass) <CLLocationManagerDelegate>
    // ... any other method declarations that subclasses need exposed can go here ...
    @end

Let me know what you think.

**Comment by Rajveer86** [comment]
Hey, no worries about the delay! The subclass file sounds like a perfect compromise, thank you :)

**Comment by smileyborg** [comment]
This should be fixed in 9ba402c608106753c321a2920e2fd04bd990a1a5. Take a look and let me know if there are any other private/internal declarations you need there.
