### ISSUE TITLE
Subscription to location updates can lead to excessive battery usage

### ISSUE THREAD

**Issue by oonoo** [intuit/LocationManager#47]
If i make a subscription to get regular position updates, the requests are never emptied thus the location manager is always running. And it is always running in the mode desiredAccuracy kCLLocationAccuracyBest. But i don't need this accuracy which needs so much battery power. I have no option to change to desiredAccuracy.

**Comment by smileyborg** [comment]
Hi @oonoo,

You are correct, INTULocationManager runs with `kCLLocationAccuracyBest`. For the regular one-time requests, this is actually not a problem, because as soon as the requested accuracy has been achieved, the request is completed, and once all requests have been completed location services are powered down.

For the newer subscription API, there is currently no way to specify the desired accuracy, which would be required to let INTULocationManager know what kind of `-[CLLocationManager desiredAccuracy]` to use.

I definitely think that this would make a good enhancement: to add another API for starting a subscription, which includes a desired accuracy parameter. (The existing subscription API will continue to default to "best".) This will require a little bit of work, because internally, INTULocationManager will need to dynamically adjust the `desiredAccuracy` setting on `CLLocationManager` based on the highest accuracy requirement of all current location requests.

Does that make sense? If you'd like to submit a pull request with this enhancement, that would be great! Otherwise it may be something that can be included with the next release (alongside #45).

**Comment by smileyborg** [comment]
Please take a look at the changes in be2dcee, I've implemented a new public API and some internal enhancements to support this!
