### ISSUE TITLE
Feature Request: Configurable Location Update Frequency

### ISSUE THREAD

**Issue by AnthonyMDev** [intuit/LocationManager#56]
I would like to be able to set a frequency for location updates, and retrieve the last known location.

In my case, I need to access the location information in my `UISearchResultsUpdater` but I don't want to actually make a location request every time the user types a character. I'd like to be able to limit it so the location actually only updates once every 2 minutes or so, and other wise, calls the completion block immediately, returning the last known location.

This would be easier if the `currentLocation` property was made public. It would be nice to seem some frequency limiting features in the library internally, but if I can access `currentLocation`, I could at least use something like `Rate Limit` (https://github.com/soffes/RateLimit) to limit my location updates and then just grab the current location.

Thoughts?

**Comment by smileyborg** [comment]
Hi Anthony,

Based on the description of your use case and desired behavior, you actually *should* be issuing a location request for search query (typed character), optionally canceling the previous location request before issuing a new one.

INTULocationManager location requests are extremely inexpensive to create, and the library is built to handle an effectively unlimited number of concurrent requests with extremely minimal overhead for each. When you ask for, say, a desired accuracy of "Neighborhood", that implies both a horizontal accuracy in meters, as well as a recency in seconds. So, whether you have just one or 100 location requests with this same Neighborhood desired accuracy, once the system location services have returned a location satisfying the "Neighborhood" accuracy, all these location requests will be completed. This is the benefit of using a singleton to centralize and manage all the active location requests.

Because of the recency component of the desired accuracy, the most recently returned location that INTULocationManager caches internally (in the `currentLocation` property) can be used to satisfy multiple location requests -- as long as the location was received within some number of seconds (based on the desired accuracy requested) from the current time. In other words, when a new location request is made, it will likely be completed near instantaneously if a previous request was recently made with at least the same accuracy level.

As far as exposing the `currentLocation` property as public, this property is kept private and internal by design -- it will never be made public. Why? This gets to one of the fundamental reasons why the INTULocationManager library exists in the first place: location services are **asynchronous**, and the API you use to access them should reflect that. Providing a public property like `currentLocation` is, in my opinion, a grave mistake, as it suggests that you can synchronously read that value at any time and immediately have the current location returned. This is obviously not the case; the block-based public API of this library makes this clear and easy to use. This is what I see as one of the greatest flaws of the Core Location API.

Does this make sense? There should be no reason to be concerned about rate limiting either calls to INTULocationManager, or the callbacks from INTULocationManager to your completion block. If you have any specific concerns that I didn't address please elaborate on those!

**Comment by smileyborg** [comment]
One other thing, your question did prompt me to take a look at the internal implementation, and I think I see a small candidate for optimization.

When a new location request comes in, we're not currently checking to see if the existing location in the `currentLocation` property (if not nil) meets the desired accuracy of the new request. As a result, even if it does, we have to wait until the next callback from CLLocationManager with an updated location to complete this new location request even though we could have completed it right away.

This isn't a very big deal in the real world, because when you first start location updates on CLLocationManager, it immediately calls you back with the most recent location it has (which will be very stale if location services weren't recently on). And if location updates are already turned on, CLLocationManager calls back about once a second with an update. So in the above scenario, the newly added request should still be completed in a second or less.

Nevertheless, if many requests are going to be submitted back to back (eg during typing), it would make sense to try and complete them immediately using the cached `currentLocation` if possible.

**Comment by AnthonyMDev** [comment]
That makes perfect sense. I didn't realize that it WOULD be using the cached location if you set the proper accuracy level. The optimization suggestion you made makes perfect sense to me. It's definitely minor, but it should be easy enough to implement that it's probably worth doing.
