### ISSUE TITLE
Possible convenience subscription to heading and location?

### ISSUE THREAD

**Issue by oliverfoggin** [intuit/LocationManager#72]
Something I do in my current app (and I imagine is done in a few apps that use location) is to subscribe to both heading and location updates in order to display a compass pointing to a particular location.

You need both the current location and the current heading in order to do this.

Do you think it would be worth adding a convenience subscription that returns both the location and heading in a single block?

**Comment by lwdupont** [comment]
I've just started to help with this repo, but that seems like a reasonable request to me. Give me a few days to check out the class and api and get back to you? Or feel free to propose something. :)

**Comment by umairqureshi6** [comment]
any update on this enhancement ?

**Comment by lwdupont** [comment]
Is it not ok to subscribe to both heading and location updates, and then update your UI as appropriate. I was looking at Apple's api, and because they are separate there, it would make it difficult to send you both accurately. The Intuit library doesn't cache results, but just passes you back the latest from Apple.
