### ISSUE TITLE
Make public requestAuthorizationIfNeeded

### ISSUE THREAD

**Issue by brightsider** [intuit/LocationManager#75]
In iOS 8 and later the maps need the request for showing an user location. Can you make requestAuthorizationIfNeeded from private to public? It would be convenient :)

**Comment by lwdupont** [comment]
Good idea, I'll take a look.

**Comment by lwdupont** [comment]
@brightsider - I was just looking at this in the source. Are you wanting that method to be exposed as a way to ask for permission before starting up the monitoring of location ? 

i.e. a convenience function for users of this framework basically? :) 

(Because when you start monitoring it will call it automatically for you).

**Comment by brightsider** [comment]
@lwdupont I want to show an user location on the map view before request an location from the location manager. I know about an authorization request when I request an location from the location manager.

**Comment by iMinichrispy** [comment]
+1 to this. Would be super cool to have a requestAuthorization method with a completion block for situations where you don't need an exact location but still need to request location permissions (like for MKMapView's showsUserLocation).

**Comment by lwdupont** [comment]
I believe this is all moot now with Apple's changes and the latest release of this. Let me know.
