### ISSUE TITLE
Will I get current location even if the app is killed or terminated ?

### ISSUE THREAD

**Issue by KrLikeblue** [intuit/LocationManager#86]
I want to get user current location even if the app is killed or terminated. And When user start walking, location must be updated even if the app is killed or terminated.. Is it possible ??

**Comment by iwasrobbed** [comment]
@KrLikeblue You can monitor for significant location changes 

https://developer.apple.com/reference/corelocation/cllocationmanager/1423531-startmonitoringsignificantlocati

>If you start this service and your app is subsequently terminated, the system automatically relaunches the app into the background if a new event arrives.

**Comment by bishtpradeep** [comment]
Does this mean that even if I have subscribed to continuous updates using **subscribeToLocationUpdatesWithBlock** my app will not get notified if application terminates. To get notified after the app has been terminated, I need to subscribe using **subscribeToSignificantLocationChangesWithBlock** _also_ and when **didFinishLaunchingWithOptions** is called with **UIApplicationLaunchOptionsLocationKey**, I need to subscribe again with **subscribeToSignificantLocationChangesWithBlock** and **subscribeToLocationUpdatesWithBlock**.

Can you please confirm ? 
Thanks.

**Comment by iwasrobbed** [comment]
@bishtpradeep Correct. If your app is terminated, you can only get location updates using significant location changes (every ~500m or so). Once you subscribe, you won't need to resubscribe (unless you unsubscribe).

**Comment by bishtpradeep** [comment]
Thank you for such a quick response.

I was not sure about the re-subscription at launch-after-termination. The README says:

**Note that when the app terminates, all of your active location requests & subscriptions with INTULocationManager are canceled. Therefore, when the app launches due to a significant location change, you should immediately use INTULocationManager to set up a new subscription for significant location changes in order to receive the location information.**

**and then in example it re-subscribes.**

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // If you start monitoring significant location changes and your app is subsequently terminated, the system automatically relaunches the app into the background if a new event arrives.
    // Upon relaunch, you must still subscribe to significant location changes to continue receiving location events. 
    if ([launchOptions objectForKey:UIApplicationLaunchOptionsLocationKey]) {
        INTULocationManager *locMgr = [INTULocationManager sharedInstance];
        [locMgr subscribeToSignificantLocationChangesWithBlock:^(CLLocation *currentLocation, INTULocationAccuracy achievedAccuracy, INTULocationStatus status) {
            // This block will be executed with the details of the significant location change that triggered the background app launch,
            // and will continue to execute for any future significant location change events as well (unless canceled).
        }];
    }
    return YES;
}

**Comment by iwasrobbed** [comment]
@bishtpradeep Apologies; it's been a while. If that's the case in the readme, then I would go that approach (re-subscribe).

**Comment by bishtpradeep** [comment]
okay. Thanks again.

**Comment by mrshyi** [comment]
Hi, @iwasrobbed thanks for the awesome lib . But in iOS11 ,maybe it is not working.

In iOS 11 startMonitoringSignificantLocationChanges working fine in background but not working if killed the app.

I am using NSLocationAlwaysAndWhenInUseUsageDescription and NSLocationWhenInUseUsageDescription both key i added in plist. Always authorization i am getting. Even in background its working fine. but if kill the app, location update is not working.
 
What i have to do fix this issue? Please help on this.

**Comment by iwasrobbed** [comment]
@mrshyi I haven't used this library in a couple of years now (and I'm not the maintainer). To be completely honest, you're probably better off just using the iOS APIs since they are fairly simple to use. Keep in mind you need to test on device and iOS 11 had a lot more privacy changes in it so I'd look around for others having issues with the significant updates.

**Comment by sheshnathiicmr** [comment]
if you are willing to use VOIP push see this link - https://www.appcaretaker.com/2018/06/05/how-to-get-iphone-ipad-current-location-even-if-app-is-terminated-not-running-in-background/

**Comment by ipsjolly** [comment]
Use FusedLocationProviderClient and start stop location updates using Broadcast instead of services as according to Android docs in future updates in os will limot assess use of services due to optimisation check location updates in background example application https://www.freakyjolly.com/android-background-geolocation-service-without-any-kill/

**Comment by kailasb** [comment]
@sheshnathiicmr link is not working. is any other option.
